services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend

  db:
    container_name: database
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    hostname: db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: